// This file is auto-generated by scripts/generate-build-id.mjs
// Do not edit this file manually - it will be overwritten on each build

export const BUILD_INFO = {
  version: "0.1.0",
  buildNumber: 128,
  commitHash: "a20b762",
  buildDate: "2026-01-04T19:21:26.531Z",
  display: "v0.1.0.128",
} as const;
