// This file is auto-generated by scripts/generate-build-id.mjs
// Do not edit this file manually - it will be overwritten on each build

export const BUILD_INFO = {
  version: "0.1.0",
  buildNumber: 92,
  commitHash: "c400a4f",
  buildDate: "2025-12-28T16:25:29.208Z",
  display: "v0.1.0.92",
} as const;
