// This file is auto-generated by scripts/generate-build-id.mjs
// Do not edit this file manually - it will be overwritten on each build

export const BUILD_INFO = {
  version: "0.1.0",
  buildNumber: 29,
  commitHash: "8b2a170",
  buildDate: "2025-12-09T12:29:11.605Z",
  display: "v0.1.0.29",
} as const;
